import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { formatSpanishDate } from '@/lib/date'

export default async function Home() {
  const supabase = await createClient()
  const [{ data: competitions }, { data: ranges }, { data: companies }] = await Promise.all([
    supabase.from('competitions').select('id,title,discipline,start_date,province,municipality,venue_name,results_url,registration_phone,poster_path').eq('status','published').order('start_date').limit(3),
    supabase.from('shooting_ranges').select('id,name,province,municipality').eq('status','published').limit(3),
    supabase.from('companies').select('id,name,company_type,province,municipality').eq('status','published').limit(3),
  ])

  return <>
    <section className="hero"><div className="shell hero-grid"><div><div className="eyebrow">Tiro deportivo · España</div><h1>Todo el tiro, en un solo lugar.</h1><p>Consulta próximas tiradas, campos, resultados, empresas y anuncios del sector desde una plataforma rápida y pensada para tiradores.</p><div className="hero-actions"><Link className="button button-light" href="/tiradas">Ver próximas tiradas</Link><Link className="button button-ghost" style={{borderColor:'rgba(255,255,255,.55)',color:'#fff'}} href="/anuncios">Explorar anuncios</Link></div></div><aside className="hero-panel"><div><span>Próximas tiradas</span><strong>{competitions?.length ?? 0}</strong><small>publicadas en la plataforma</small></div><div><span>Directorio</span><strong>{(ranges?.length ?? 0)+(companies?.length ?? 0)}</strong><small>campos y empresas visibles</small></div></aside></div></section>
    <div className="shell search-box"><input className="input" placeholder="Buscar tiradas, campos, empresas o material…"/><select defaultValue="todo"><option value="todo">Todo</option><option>Tiradas</option><option>Campos</option><option>Empresas</option><option>Anuncios</option></select><button className="button">Buscar</button></div>
    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow muted">Calendario</div><h2>Próximas tiradas</h2></div><Link className="text-link" href="/tiradas">Ver calendario completo →</Link></div>{competitions?.length ? <div className="cards competition-cards">{competitions.map(c=>{const posterUrl=c.poster_path?supabase.storage.from('competition-assets').getPublicUrl(c.poster_path).data.publicUrl:null;return <article className="card competition-card" key={c.id}>{posterUrl?<a className="competition-poster-link" href={posterUrl} target="_blank" rel="noreferrer" title="Ver cartel a tamaño completo"><img className="competition-poster" src={posterUrl} alt={`Cartel de ${c.title}`}/></a>:<div className="competition-poster-placeholder">Sin cartel</div>}<div className="competition-card-body"><span className="date-badge">{formatSpanishDate(c.start_date,{day:'2-digit',month:'short'})}</span><h3>{c.title}</h3><p className="muted">{c.discipline} · {[c.municipality,c.province].filter(Boolean).join(', ')}</p>{c.registration_phone&&<p><b>Inscripción:</b> <a className="text-link" href={`tel:${c.registration_phone.replace(/\s+/g,'')}`}>{c.registration_phone}</a></p>}{c.results_url&&<a className="text-link" href={c.results_url} target="_blank" rel="noreferrer">Resultados en directo →</a>}</div></article>})}</div>:<div className="empty">Aún no hay tiradas publicadas. El panel de administración será quien las alimente.</div>}</div></section>
    <section className="feature-strip"><div className="shell features"><div className="feature"><b>Tiradas</b><span className="muted">Fechas, modalidades, carteles y resultados.</span></div><div className="feature"><b>Campos</b><span className="muted">Directorio nacional organizado por ubicación.</span></div><div className="feature"><b>Empresas</b><span className="muted">Profesionales y servicios del sector.</span></div><div className="feature"><b>Anuncios</b><span className="muted">Publicaciones moderadas y fotografías detalladas.</span></div></div></section>
    <section className="section"><div className="shell"><div className="section-head"><div><div className="eyebrow muted">Comunidad</div><h2>Un portal que sirva cada semana</h2></div></div><div className="cards"><article className="card"><span className="pill">01</span><h3>Consulta el calendario</h3><p className="muted">Encuentra competiciones por fecha, provincia y modalidad.</p></article><article className="card"><span className="pill">02</span><h3>Sigue los resultados</h3><p className="muted">Accede a enlaces oficiales y clasificaciones cuando estén disponibles.</p></article><article className="card"><span className="pill">03</span><h3>Descubre el sector</h3><p className="muted">Campos, clubes, empresas y publicaciones en un mismo sitio.</p></article></div></div></section>
  </>
}
